name: fourtynine_dashboard
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: ^4.6.6
  dio: ^5.4.0
  http: ^1.2.0
  pretty_dio_logger: ^1.3.1
  textless: 6.6.6
  cached_network_image: ^3.3.1
  image_picker: 0.8.5+3
  file_picker: ^5.0.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  intl: ^0.17.0
  timeago: ^3.3.0
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  flutter_bloc: ^8.1.6
  pdfx:
    git:
      url: 'https://github.com/ScerIO/packages.flutter'
      ref: '4be9de9ffed5398fd7d5f44bbb07dcd3d3f1711b'
      path: packages/pdfx
  equatable: ^2.0.5
  animated_text_kit: ^4.2.2
  sliver_tools: ^0.2.12
  just_audio: ^0.9.36
  chewie: ^1.3.4
  font_awesome_flutter: 10.2.1
  readmore: ^2.2.0
  flutter_rating_stars: 1.0.3+4
  url_launcher: 6.1.5
  maps_launcher: ^2.2.1
  audio_waveforms: 0.1.5+1
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true

