part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const ChangeUserNameAndPass = _Paths.CHANGEUSERNAMEANDPASS;
  static const LOGIN = _Paths.LOGIN;
  static const SUPER_HOME = _Paths.SUPER_HOME;
  static const USERS = _Paths.USERS;
  static const USER_DETAILS = _Paths.USER_DETAILS;
  static const APP_MANAGER = _Paths.APP_MANAGER;
  static const SUB_CATEGORY = _Paths.SUB_CATEGORY;
  static const MAIN_CATEGORY = _Paths.MAIN_CATEGORY;
  static const ADD_SUB_CATEGORY = _Paths.ADD_SUB_CATEGORY;
  static const RUNNING_COST = _Paths.RUNNING_COST;
  static const ADMINS = _Paths.ADMINS;
  static const REVIEW_ADS = _Paths.REVIEW_ADS;
  static const SINGLE_AD_DETAILS = _Paths.SINGLE_AD_DETAILS;
  static const REVIEW_RIDE = _Paths.REVIEW_RIDE;
  static const IMAGES_VIEWER = _Paths.IMAGES_VIEWER;
  static const REVIEW_LOADING = _Paths.REVIEW_LOADING;
  static const REVIEW_RESTAURANT = _Paths.REVIEW_RESTAURANT;
  static const REVIEW_HEALTH = _Paths.REVIEW_HEALTH;
  static const REVIEW_FOOD = _Paths.REVIEW_FOOD;
  static const ADMIN_MAIN_CATEGORY = _Paths.ADMIN_MAIN_CATEGORY;
  static const ADMIN_SUB_CATEGORY = _Paths.ADMIN_SUB_CATEGORY;
  static const DYNAMIC_PROPS = _Paths.DYNAMIC_PROPS;
  static const ADMIN_USERS = _Paths.ADMIN_USERS;
  static const GIFTS = _Paths.GIFTS;
  static const POST_ACTIVITY = _Paths.POST_ACTIVITY;
  static const POST_FEELING = _Paths.POST_FEELING;
  static const SONGS = _Paths.SONGS;
  static const APP_RADIO = _Paths.APP_RADIO;
  static const DYNAMIC_ADS = _Paths.DYNAMIC_ADS;
  static const RESTAURANTS = _Paths.RESTAURANTS;
  static const RIDERS = _Paths.RIDERS;
  static const LOADINGS = _Paths.LOADINGS;
  static const DOCTORS = _Paths.DOCTORS;
  static const USER_REFERRALS = _Paths.USER_REFERRALS;
  static const REPORTS = _Paths.REPORTS;
  static const OTHER_USER_PROFILE = _Paths.OTHER_USER_PROFILE;
  static const SINGLE_POST = _Paths.SINGLE_POST;
  static const DYNAMIC_AD_DETAILS = _Paths.DYNAMIC_AD_DETAILS;
  static const RESTAURANT_DETAILS = _Paths.RESTAURANT_DETAILS;
  static const DOCTOR_DETAILS = _Paths.DOCTOR_DETAILS;
  static const MESSAGE = _Paths.MESSAGE;
  static const COME_WITH_ME_TRIPS = _Paths.COME_WITH_ME_TRIPS;
  static const REVIEW_COME_WITH_ME_TRIPS = _Paths.REVIEW_COME_WITH_ME_TRIPS;
  static const PICK_ME_TRIPS = _Paths.PICK_ME_TRIPS;
  static const REVIEW_PICK_ME_TRIPS = _Paths.REVIEW_PICK_ME_TRIPS;
  static const MONTHLY_CONTEST = _Paths.MONTHLY_CONTEST;
  static const COMPLAINTS = _Paths.COMPLAINTS;
  static const ALLUSERSPROFILES = _Paths.ALLUSERSPROFILES;
  static const USERPROFILE = _Paths.USERPROFILE;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const CHANGEUSERNAMEANDPASS = '/changeUserName';
  static const LOGIN = '/login';
  static const SUPER_HOME = '/super-home';
  static const USERS = '/users';
  static const USER_DETAILS = '/user-details';
  static const APP_MANAGER = '/app-manager';
  static const SUB_CATEGORY = '/sub-category';
  static const MAIN_CATEGORY = '/main-category';
  static const ADD_SUB_CATEGORY = '/add-sub-category';
  static const RUNNING_COST = '/running-cost';
  static const ADMINS = '/admins';
  static const REVIEW_ADS = '/review-ads';
  static const SINGLE_AD_DETAILS = '/single-ad-details';
  static const DYNAMIC_AD_DETAILS = '/DYNAMIC-ad-details';

  static const REVIEW_RIDE = '/review-ride';
  static const IMAGES_VIEWER = '/images-viewer';
  static const REVIEW_LOADING = '/review-loading';
  static const REVIEW_RESTAURANT = '/review-restaurant';
  static const REVIEW_HEALTH = '/review-health';
  static const REVIEW_FOOD = '/review-food';
  static const ADMIN_MAIN_CATEGORY = '/admin-main-category';
  static const ADMIN_SUB_CATEGORY = '/admin-sub-category';
  static const DYNAMIC_PROPS = '/dynamic-props';
  static const ADMIN_USERS = '/admin-users';
  static const GIFTS = '/gifts';
  static const POST_ACTIVITY = '/post-activity';
  static const POST_FEELING = '/post-feeling';
  static const SONGS = '/songs';
  static const APP_RADIO = '/app-radio';
  static const DYNAMIC_ADS = '/dynamic-ads';
  static const RESTAURANTS = '/restaurants';
  static const RIDERS = '/riders';
  static const LOADINGS = '/loadings';
  static const DOCTORS = '/doctors';
  static const USER_REFERRALS = '/user-referrals';
  static const REPORTS = '/reports';
  static const OTHER_USER_PROFILE = '/OTHER_USER_PROFILE';
  static const SINGLE_POST = '/single-post';
  static const RESTAURANT_DETAILS = '/RESTAURANT_DETAILS';
  static const DOCTOR_DETAILS = '/DOCTOR_DETAILS';
  static const MESSAGE = '/message';
  static const COME_WITH_ME_TRIPS = '/come-with-me-trips';
  static const REVIEW_COME_WITH_ME_TRIPS = '/review-come-with-me-trips';
  static const PICK_ME_TRIPS = '/pick-me-trips';
  static const REVIEW_PICK_ME_TRIPS = '/review-pick-me-trips';
  static const MONTHLY_CONTEST = '/monthly-contest';
  static const COMPLAINTS = '/complaints';
  static const ALLUSERSPROFILES = '/all-users-profiles';
  static const USERPROFILE = '/user-profile';
}
